import { ThemeMetadata } from '@/theme-engine/types';

export const auroraThemeMeta: ThemeMetadata = {
  id: 'aurora',
  name: 'Aurora Minimalist',
  version: '1.0.0',
  tagline: 'Modern, Elegan, & Penuh Gaya',
  description: 'Desain minimalis cinematic dengan palet dark slate, tipografi tegas, dan foto-foto dramatis hitam putih.',
  category: 'Modern Minimalist',
  previewColor: '#607D8B',
  defaultColors: {
    primary: '#607D8B',
    secondary: '#455A64',
    background: '#FAFAFA',
    accent: '#B0BEC5',
    text: '#1E252B',
    surface: '#FFFFFF',
  },
  customizableColors: [
    { key: 'primary', label: 'Warna Utama', type: 'color' },
    { key: 'secondary', label: 'Warna Sekunder', type: 'color' },
    { key: 'background', label: 'Warna Latar Belakang', type: 'color' },
    { key: 'surface', label: 'Warna Kartu / Konten', type: 'color' },
    { key: 'text', label: 'Warna Teks Utama', type: 'color' },
  ],
  defaultFonts: {
    heading: 'Cormorant Garamond',
    body: 'Inter',
  },
  defaultTokens: {
    '--theme-primary': '#607D8B',
    '--theme-primary-hover': '#546E7A',
    '--theme-secondary': '#455A64',
    '--theme-accent': '#B0BEC5',
    '--theme-bg': '#FAFAFA',
    '--theme-surface': '#FFFFFF',
    '--theme-surface-alt': '#FAFAFA',
    '--theme-text': '#1E252B',
    '--theme-text-muted': '#6B7280',
    '--theme-text-accent': '#607D8B',
    '--theme-border': '#E5E7EB',
    '--theme-border-accent': '#B0BEC5',
    '--font-heading': "'Cormorant Garamond', serif",
    '--font-body': "'Inter', sans-serif",
  },
  supportedSections: [
    'cover', 'couple', 'event', 'countdown',
    'gallery', 'rsvp', 'guestbook', 'closing',
  ],
  capabilities: {
    supportsGallery: true,
    supportsMusicPlayer: false,
    supportsCountdown: true,
    supportsGuestbook: true,
    supportsGift: false,
    supportsLoveStory: false,
  },
  tags: ['minimalist', 'modern', 'cinematic', 'dark'],
};
