import { ThemeMetadata } from '@/theme-engine/types';

export const serenityThemeMeta: ThemeMetadata = {
  id: 'serenity',
  name: 'Serenity Pastels',
  version: '1.0.0',
  tagline: 'Lembut, Manis, & Penuh Kehangatan',
  description: 'Desain romantis dengan sentuhan warna pastel rose quartz, aksen emas halus, dan tipografi kaligrafi klasik.',
  category: 'Romantic Classic',
  previewColor: '#FCBACB',
  defaultColors: {
    primary: '#FCBACB',
    secondary: '#FC9FB1',
    background: '#FCFCFC',
    accent: '#FFEAAB',
    text: '#263238',
    textMuted: '#6B7280',
  },
  customizableColors: [
    { key: 'primary', label: 'Warna Utama', type: 'color' },
    { key: 'secondary', label: 'Warna Sekunder', type: 'color' },
    { key: 'accent', label: 'Warna Aksen', type: 'color' },
    { key: 'background', label: 'Warna Latar Belakang', type: 'color' },
    { key: 'text', label: 'Warna Teks Utama', type: 'color' },
    { key: 'textMuted', label: 'Warna Teks Redup', type: 'color' },
  ],
  defaultFonts: {
    heading: 'Quintessential',
    body: 'Inter',
  },
  defaultTokens: {
    '--theme-primary': '#FCBACB',
    '--theme-primary-hover': '#FC9FB1',
    '--theme-secondary': '#FC9FB1',
    '--theme-accent': '#FFEAAB',
    '--theme-bg': '#FCFCFC',
    '--theme-surface': '#FFFFFF',
    '--theme-surface-alt': '#FFF8FA',
    '--theme-text': '#263238',
    '--theme-text-muted': '#6B7280',
    '--theme-text-accent': '#D96F88',
    '--theme-border': '#F1F5F9',
    '--theme-border-accent': '#FCBACB',
    '--font-heading': "'Quintessential', cursive",
    '--font-body': "'Inter', sans-serif",
  },
  supportedSections: [
    'cover', 'couple', 'story', 'event', 'countdown',
    'gallery', 'gift', 'rsvp', 'guestbook', 'closing',
  ],
  capabilities: {
    supportsGallery: true,
    supportsMusicPlayer: true,
    supportsCountdown: true,
    supportsGuestbook: true,
    supportsGift: true,
    supportsLoveStory: true,
  },
  tags: ['romantic', 'pastel', 'classic', 'pink'],
};
