import {
  User,
  Wedding,
  Invitation,
  Guest,
  RSVP,
  GuestbookEntry,
  PlannerTask,
  BudgetItem,
  Vendor,
} from '@kisahmagis/types';

export const INITIAL_USER: User = {
  id: 'user-andi-sari',
  name: 'Andi & Sari',
  email: 'andi@kisahmagis.id',
  createdAt: '2026-01-10T10:00:00Z',
};

export const INITIAL_WEDDING: Wedding = {
  id: 'wedding-andi-sari',
  ownerId: 'user-andi-sari',
  slug: 'andi-sari',
  title: 'The Wedding of Andi & Sari',
  groomName: 'Andi Pratama, S.T.',
  groomParents: 'Putra pertama dari Bpk. Bambang Wijaya & Ibu Siti Rahayu',
  groomBio: 'Pria yang menyukai fotografi, kopi hitam, dan selalu bersyukur menemukan sosok pendamping yang hangat.',
  groomPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
  groomInstagram: '@andipratama',
  
  brideName: 'Sari Kusuma Wardani, S.Ds.',
  brideParents: 'Putri kedua dari Bpk. Hendra Kusuma & Ibu Dewi Anggraini',
  brideBio: 'Desainer yang mencintai seni, tanaman hias, dan cerita dongeng yang kini menjadi kenyataan.',
  bridePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
  brideInstagram: '@sarikusuma',
  
  weddingDate: '2026-12-20T08:00:00Z',
  status: 'published',
  coverPhoto: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
  
  akadEvent: {
    title: 'Akad Nikah',
    date: 'Minggu, 20 Desember 2026',
    time: '08:00 - 10:00 WIB',
    venue: 'Masjid Agung Al-Azhar',
    address: 'Jl. Sisingamangaraja No.1, Kebayoran Baru, Jakarta Selatan',
    mapUrl: 'https://maps.google.com/?q=Masjid+Agung+Al-Azhar+Jakarta',
  },
  receptionEvent: {
    title: 'Resepsi Pernikahan',
    date: 'Minggu, 20 Desember 2026',
    time: '11:00 - 14:00 WIB',
    venue: 'Plataran Dharmawangsa',
    address: 'Jl. Dharmawangsa Raya No.6, Pulo, Kebayoran Baru, Jakarta Selatan',
    mapUrl: 'https://maps.google.com/?q=Plataran+Dharmawangsa+Jakarta',
  },
  
  stories: [
    {
      id: 'story-1',
      year: '2020',
      title: 'Awal Bertemu',
      story: 'Takdir mempertemukan kami di sebuah sore yang tenang di perpustakaan kampus. Obrolan singkat tentang buku arsitektur membuka lembaran kisah yang tak terduga.',
      image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'story-2',
      year: '2022',
      title: 'Menjalin Kasih',
      story: 'Dua tahun saling mengenal, kami memutuskan untuk saling mendampingi dalam suka maupun duka, saling tumbuh dan menguatkan mimpi bersama.',
      image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'story-3',
      year: '2025',
      title: 'Janji di Bromo',
      story: 'Di bawah matahari terbit Gunung Bromo yang sejuk, Andi mengutarakan niat tulus untuk melangkah ke jenjang pernikahan. Dan Sari menjawab dengan senyuman "Ya".',
      image: 'https://images.unsplash.com/photo-1529636798458-92182e662485?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'story-4',
      year: '2026',
      title: 'Menuju Hari Bahagia',
      story: 'Dengan restu kedua orang tua dan doa dari para sahabat, kami bersiap merajut babak baru kehidupan bersama.',
      image: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=600&q=80',
    },
  ],
  
  gifts: [
    {
      id: 'gift-1',
      bankName: 'BCA',
      accountNumber: '5271239845',
      accountHolder: 'Andi Pratama',
    },
    {
      id: 'gift-2',
      bankName: 'Bank Mandiri',
      accountNumber: '1370019284751',
      accountHolder: 'Sari Kusuma Wardani',
    },
  ],
  
  createdAt: '2026-01-10T10:00:00Z',
  updatedAt: '2026-01-15T10:00:00Z',
};

export const INITIAL_INVITATION: Invitation = {
  id: 'invitation-andi-sari',
  weddingId: 'wedding-andi-sari',
  status: 'published',
  publishedAt: '2026-01-15T12:00:00Z',
  updatedAt: '2026-01-15T12:00:00Z',
  config: {
    themeId: 'serenity',
    themeVersion: '1.0.0',
    colors: {
      primary: '#FCBACB',
      secondary: '#FC9FB1',
      background: '#FCFCFC',
      accent: '#FFEAAB',
    },
    fonts: {
      heading: 'Quintessential',
      body: 'Inter',
    },
    sections: [
      { type: 'cover', enabled: true, order: 1 },
      { type: 'couple', enabled: true, order: 2 },
      { type: 'story', enabled: true, order: 3 },
      { type: 'event', enabled: true, order: 4 },
      { type: 'countdown', enabled: true, order: 5 },
      { type: 'gallery', enabled: true, order: 6 },
      { type: 'gift', enabled: true, order: 7 },
      { type: 'rsvp', enabled: true, order: 8 },
      { type: 'guestbook', enabled: true, order: 9 },
      { type: 'closing', enabled: true, order: 10 },
    ],
    music: {
      enabled: true,
      title: 'A Thousand Years (Acoustic)',
      artist: 'KisahMagis Instrumental Ensemble',
      url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-113222.mp3',
    },
    gallery: {
      layout: 'masonry',
      images: [
        { id: 'img-1', url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', caption: 'Momen berdua di taman' },
        { id: 'img-2', url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80', caption: 'Senyum yang menyejukkan hati' },
        { id: 'img-3', url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80', caption: 'Janji suci di hadapan alam' },
        { id: 'img-4', url: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80', caption: 'Tertawa bersama melangkah' },
        { id: 'img-5', url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80', caption: 'Keindahan dalam kesederhanaan' },
        { id: 'img-6', url: 'https://images.unsplash.com/photo-1519225429980-715cb0215aed?auto=format&fit=crop&w=800&q=80', caption: 'Dekorasi hangat dan intim' },
      ],
    },
    quote: {
      text: '“Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.”',
      source: 'QS. Ar-Rum: 21',
    },
  },
};

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'guest-1',
    weddingId: 'wedding-andi-sari',
    name: 'Budi Santoso & Partner',
    phone: '081234567890',
    email: 'budi@example.com',
    group: 'Sahabat',
    invitationToken: 'BudiS88',
    invitationStatus: 'viewed',
    rsvpStatus: 'attending',
    guestCount: 2,
    createdAt: '2026-01-12T09:00:00Z',
    updatedAt: '2026-01-15T14:30:00Z',
  },
  {
    id: 'guest-2',
    weddingId: 'wedding-andi-sari',
    name: 'Dian Permata Sari',
    phone: '081398765432',
    email: 'dian@example.com',
    group: 'VIP',
    invitationToken: 'DianP23',
    invitationStatus: 'viewed',
    rsvpStatus: 'attending',
    guestCount: 1,
    createdAt: '2026-01-12T09:15:00Z',
    updatedAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 'guest-3',
    weddingId: 'wedding-andi-sari',
    name: 'Keluarga Bpk. Rahmat Hidayat',
    phone: '085711223344',
    email: '',
    group: 'Keluarga',
    invitationToken: 'RahmatK5',
    invitationStatus: 'sent',
    rsvpStatus: 'pending',
    guestCount: 4,
    createdAt: '2026-01-13T10:00:00Z',
    updatedAt: '2026-01-13T10:00:00Z',
  },
  {
    id: 'guest-4',
    weddingId: 'wedding-andi-sari',
    name: 'Rian Pratama & Tim Desain',
    phone: '087812983476',
    email: 'rian@studio.com',
    group: 'Rekan Kerja',
    invitationToken: 'RianP99',
    invitationStatus: 'viewed',
    rsvpStatus: 'declined',
    guestCount: 1,
    createdAt: '2026-01-13T11:00:00Z',
    updatedAt: '2026-01-17T16:20:00Z',
  },
  {
    id: 'guest-5',
    weddingId: 'wedding-andi-sari',
    name: 'Dr. Hendro & Istri',
    phone: '081122334455',
    email: '',
    group: 'VIP',
    invitationToken: 'HendroV1',
    invitationStatus: 'pending',
    rsvpStatus: 'pending',
    guestCount: 2,
    createdAt: '2026-01-14T08:00:00Z',
    updatedAt: '2026-01-14T08:00:00Z',
  },
];

export const INITIAL_RSVPS: RSVP[] = [
  {
    id: 'rsvp-1',
    weddingId: 'wedding-andi-sari',
    guestId: 'guest-1',
    name: 'Budi Santoso & Partner',
    attendance: 'attending',
    guestCount: 2,
    message: 'Selamat untuk Andi & Sari! Sangat bersyukur melihat perjalanan kalian sampai hari ini.',
    submittedAt: '2026-01-15T14:30:00Z',
  },
  {
    id: 'rsvp-2',
    weddingId: 'wedding-andi-sari',
    guestId: 'guest-2',
    name: 'Dian Permata Sari',
    attendance: 'attending',
    guestCount: 1,
    message: 'Happy wedding! Semoga menjadi keluarga yang sakinah, mawaddah, warahmah. Aamiin!',
    submittedAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 'rsvp-3',
    weddingId: 'wedding-andi-sari',
    guestId: 'guest-4',
    name: 'Rian Pratama & Tim Desain',
    attendance: 'declined',
    guestCount: 1,
    message: 'Maaf belum bisa hadir karena ada dinas luar kota, tapi doa terbaik selalu menyertai kalian berdua!',
    submittedAt: '2026-01-17T16:20:00Z',
  },
];

export const INITIAL_GUESTBOOK: GuestbookEntry[] = [
  {
    id: 'gb-1',
    weddingId: 'wedding-andi-sari',
    guestName: 'Budi Santoso',
    message: 'Selamat menempuh hidup baru sahabatku Andi & Sari! Semoga rukun selamanya hingga kakek nenek.',
    isApproved: true,
    createdAt: '2026-01-15T14:35:00Z',
  },
  {
    id: 'gb-2',
    weddingId: 'wedding-andi-sari',
    guestName: 'Dian Permata',
    message: 'Cantik banget Sari, selamat yaa! Bahagia selalu berdua bersama Andi.',
    isApproved: true,
    createdAt: '2026-01-16T10:05:00Z',
  },
  {
    id: 'gb-3',
    weddingId: 'wedding-andi-sari',
    guestName: 'Keluarga Bpk. Wijaya',
    message: 'Semoga Allah senantiasa memberkahi pernikahan ini dengan cinta dan keberlimpahan.',
    isApproved: true,
    createdAt: '2026-01-18T09:20:00Z',
  },
];

export const INITIAL_TASKS: PlannerTask[] = [
  {
    id: 'task-1',
    weddingId: 'wedding-andi-sari',
    columnId: 'done',
    title: 'Booking Venue Plataran Dharmawangsa',
    description: 'Konfirmasi tanggal 20 Desember 2026 dan serah terima DP 30%.',
    priority: 'high',
    category: 'Venue',
    dueDate: '2026-02-01',
    order: 1,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'task-2',
    weddingId: 'wedding-andi-sari',
    columnId: 'done',
    title: 'Pilih Cincin Pernikahan',
    description: 'Cincin emas putih custom grafir nama & tanggal.',
    priority: 'medium',
    category: 'Perhiasan',
    dueDate: '2026-02-15',
    order: 2,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'task-3',
    weddingId: 'wedding-andi-sari',
    columnId: 'in_progress',
    title: 'Penyusunan Rundown Akad & Resepsi',
    description: 'Sinkronisasi jadwal bersama Wedding Organizer & keluarga besar.',
    priority: 'high',
    category: 'Organisasi',
    dueDate: '2026-10-15',
    order: 1,
    createdAt: '2026-01-11T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'task-4',
    weddingId: 'wedding-andi-sari',
    columnId: 'in_progress',
    title: 'Distribusi Undangan Digital via WhatsApp',
    description: 'Kirim link personal ke tamu VIP dan sahabat.',
    priority: 'high',
    category: 'Undangan',
    dueDate: '2026-11-01',
    order: 2,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-16T10:00:00Z',
  },
  {
    id: 'task-5',
    weddingId: 'wedding-andi-sari',
    columnId: 'todo',
    title: 'Finalisasi Daftar Lagu Pengiring',
    description: 'Pilih 10 lagu akustik romantis untuk resepsi santai.',
    priority: 'low',
    category: 'Hiburan',
    dueDate: '2026-11-20',
    order: 1,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'task-6',
    weddingId: 'wedding-andi-sari',
    columnId: 'todo',
    title: 'Fitting Baju Pengantin Terakhir',
    description: 'Fitting busana akad & resepsi bersama desainer.',
    priority: 'medium',
    category: 'Busana',
    dueDate: '2026-12-05',
    order: 2,
    createdAt: '2026-01-13T10:00:00Z',
    updatedAt: '2026-01-13T10:00:00Z',
  },
];

export const INITIAL_BUDGET: BudgetItem[] = [
  {
    id: 'b-1',
    weddingId: 'wedding-andi-sari',
    category: 'Venue & Katering',
    name: 'Paket Plataran Dharmawangsa (500 pax)',
    estimatedCost: 120000000,
    actualCost: 115000000,
    paidAmount: 115000000,
    paymentStatus: 'paid',
    notes: 'Sudah termasuk sound system dasar dan test food',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'b-2',
    weddingId: 'wedding-andi-sari',
    category: 'Dekorasi',
    name: 'Dekorasi Pelaminan & Area Resepsi',
    estimatedCost: 28000000,
    actualCost: 25000000,
    paidAmount: 15000000,
    paymentStatus: 'partial',
    notes: 'Tema botanical pastel with warm lighting',
    createdAt: '2026-01-11T10:00:00Z',
    updatedAt: '2026-01-11T10:00:00Z',
  },
  {
    id: 'b-3',
    weddingId: 'wedding-andi-sari',
    category: 'Foto & Video',
    name: 'Dokumentasi Prewedding & Hari H',
    estimatedCost: 20000000,
    actualCost: 18000000,
    paidAmount: 18000000,
    paymentStatus: 'paid',
    notes: 'Termasuk 2 fotografer, 1 videografer, teaser 1 menit & full album',
    createdAt: '2026-01-11T10:00:00Z',
    updatedAt: '2026-01-11T10:00:00Z',
  },
  {
    id: 'b-4',
    weddingId: 'wedding-andi-sari',
    category: 'Busana & Rias',
    name: 'Busana Pengantin & MUA Flawless',
    estimatedCost: 15000000,
    actualCost: 16000000,
    paidAmount: 10000000,
    paymentStatus: 'partial',
    notes: 'Busana akad adat modern + gaun resepsi',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'b-5',
    weddingId: 'wedding-andi-sari',
    category: 'Undangan & Souvenir',
    name: 'Souvenir Custom Eco Tumbler (300 pcs)',
    estimatedCost: 9000000,
    actualCost: 8500000,
    paidAmount: 0,
    paymentStatus: 'unpaid',
    notes: 'Selesai cetak H-20',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'b-6',
    weddingId: 'wedding-andi-sari',
    category: 'Hiburan & Sound',
    name: 'Acoustic Trio Ensemble',
    estimatedCost: 12000000,
    actualCost: 11000000,
    paidAmount: 11000000,
    paymentStatus: 'paid',
    notes: 'Vokal, Piano/Gitar, Cello',
    createdAt: '2026-01-13T10:00:00Z',
    updatedAt: '2026-01-13T10:00:00Z',
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    weddingId: 'wedding-andi-sari',
    name: 'Plataran Dharmawangsa',
    category: 'Venue',
    contactPerson: 'Ibu Ratna',
    phone: '081298761234',
    instagram: '@plataran.dharmawangsa',
    cost: 115000000,
    status: 'booked',
    notes: 'Kapasitas maksimal 600 tamu, parkir luas, izin keramaian diurus venue.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'vendor-2',
    weddingId: 'wedding-andi-sari',
    name: 'Magis Botanical Decor',
    category: 'Decoration',
    contactPerson: 'Mas Bayu',
    phone: '081345678901',
    instagram: '@magisdecor',
    cost: 25000000,
    status: 'booked',
    notes: 'Nuansa soft pink, cream, dan dedaunan segar.',
    createdAt: '2026-01-11T10:00:00Z',
    updatedAt: '2026-01-11T10:00:00Z',
  },
  {
    id: 'vendor-3',
    weddingId: 'wedding-andi-sari',
    name: 'Lumiere Cinematic Stories',
    category: 'Photography',
    contactPerson: 'Gilang',
    phone: '087811223344',
    instagram: '@lumierestories',
    cost: 18000000,
    status: 'booked',
    notes: 'Tone warm and romantic, sudah termasuk drone shot.',
    createdAt: '2026-01-11T10:00:00Z',
    updatedAt: '2026-01-11T10:00:00Z',
  },
  {
    id: 'vendor-4',
    weddingId: 'wedding-andi-sari',
    name: 'Anggun Atelier & Makeup',
    category: 'Attire & Makeup',
    contactPerson: 'Mbak Anggun',
    phone: '085699887766',
    instagram: '@anggunatelier',
    cost: 16000000,
    status: 'booked',
    notes: 'MUA include retouch untuk resepsi.',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
];
