import { ThemeMetadata } from '@/theme-engine/types';

export const bloomThemeMeta: ThemeMetadata = {
  id: 'bloom',
  name: 'Bloom Botanical',
  version: '1.0.0',
  tagline: 'Segar, Alami, & Penuh Kehidupan',
  description: 'Desain botanical dengan palet hijau segar, tekstur daun, dan tipografi elegan bernuansa alam.',
  category: 'Botanical Nature',
  previewColor: '#B9DCA9',
  defaultColors: {
    primary: '#B9DCA9',
    secondary: '#74A12E',
    background: '#FDFBF7',
    accent: '#D5E8D4',
    text: '#2C352E',
    border: '#E8E6DC',
  },
  customizableColors: [
    { key: 'primary', label: 'Warna Utama', type: 'color' },
    { key: 'secondary', label: 'Warna Sekunder', type: 'color' },
    { key: 'background', label: 'Warna Latar Belakang', type: 'color' },
    { key: 'text', label: 'Warna Teks Utama', type: 'color' },
    { key: 'border', label: 'Warna Garis Pembatas', type: 'color' },
  ],
  defaultFonts: {
    heading: 'Playfair Display',
    body: 'Inter',
  },
  defaultTokens: {
    '--theme-primary': '#B9DCA9',
    '--theme-primary-hover': '#A3CE90',
    '--theme-secondary': '#74A12E',
    '--theme-accent': '#D5E8D4',
    '--theme-bg': '#FDFBF7',
    '--theme-surface': '#FFFFFF',
    '--theme-surface-alt': '#F9F7F0',
    '--theme-text': '#2C352E',
    '--theme-text-muted': '#6B7280',
    '--theme-text-accent': '#5A8220',
    '--theme-border': '#E8E6DC',
    '--theme-border-accent': '#B9DCA9',
    '--font-heading': "'Playfair Display', serif",
    '--font-body': "'Inter', sans-serif",
  },
  supportedSections: [
    'cover', 'couple', 'story', 'event', 'countdown',
    'gallery', 'gift', 'rsvp', 'guestbook', 'closing',
  ],
  capabilities: {
    supportsGallery: true,
    supportsMusicPlayer: true,
    supportsCountdown: true,
    supportsGuestbook: true,
    supportsGift: true,
    supportsLoveStory: true,
  },
  tags: ['botanical', 'green', 'nature', 'fresh'],
};
